services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_DOCKER_PORT: 3000
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: onmula
      DB_NAME: ufc
      DB_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: onmula
      POSTGRES_DB: ufc
    volumes:
      - ./ufcfin.sql:/docker-entrypoint-initdb.d/ufcfin.sql

volumes:
  ufcvolume:
